import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../services/anilist_service.dart';
import '../themes/themes.dart';
import '../controllers/theme_controller.dart';
import '../controllers/catalog_controller.dart';

class HomeView extends StatefulWidget { const HomeView({super.key}); @override State<HomeView> createState()=>_HomeViewState(); }
class _HomeViewState extends State<HomeView> {
  late Future<List<AniListMedia>> trending;
  late Future<List<AniListMedia>> popular;
  @override void initState(){super.initState();trending=AniListService.browse('TRENDING_DESC');popular=AniListService.browse('POPULARITY_DESC');}
  Widget section(String title,Future<List<AniListMedia>> future){return FutureBuilder<List<AniListMedia>>(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const SizedBox(height:250,child:Center(child:CircularProgressIndicator()));if(!s.hasData||s.data!.isEmpty)return const SizedBox.shrink();final items=s.data!;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Padding(padding:const EdgeInsets.fromLTRB(16,22,16,10),child:Text(title,style:Theme.of(c).textTheme.titleLarge)),SizedBox(height:255,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,itemCount:items.length,itemBuilder:(_,i)=>PosterCard(media:items[i]),separatorBuilder:(_,__)=>const SizedBox(width:12))) ]);});}
  @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(body:SafeArea(child:CustomScrollView(slivers:[SliverAppBar(pinned:true,title:Row(children:[Image.asset('assets/images/aniloop_logo.png',width:34,height:34),const SizedBox(width:9),const Text('AniLoop',style:TextStyle(fontWeight:FontWeight.w900))]),actions:[IconButton(onPressed:()=>Get.find<ThemeController>().toggle(),icon:Icon(dark?Icons.light_mode_rounded:Icons.dark_mode_rounded)),IconButton(onPressed:()=>showSearch(context:context,delegate:AniLoopSearchDelegate()),icon:const Icon(Icons.search_rounded))]),SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,16,16,0),child:const HeroBanner())),SliverToBoxAdapter(child:section('Trending Now',trending)),SliverToBoxAdapter(child:section('Most Popular',popular)),SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,28,16,10),child:Text('Source Library',style:Theme.of(context).textTheme.titleLarge))),SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,0,16,35),child:FilledButton.icon(onPressed:(){Get.find<CatalogController>().update(['pageView']);},icon:const Icon(Icons.movie_filter_rounded),label:const Padding(padding:EdgeInsets.symmetric(vertical:14),child:Text('Browse all sources'))))])));}
}
class HeroBanner extends StatelessWidget{const HeroBanner({super.key});@override Widget build(BuildContext c){return Container(height:210,decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(colors:[Color(0xFF321025),Color(0xFF111827)],begin:Alignment.topLeft,end:Alignment.bottomRight),boxShadow:const[BoxShadow(blurRadius:30,offset:Offset(0,12),color:Colors.black54)]),child:Stack(children:[Positioned(right:-30,top:-40,child:Icon(Icons.play_circle_fill_rounded,size:230,color:Themes.accent.withOpacity(.18))),const Padding(padding:EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Spacer(),Text('YOUR ANIME.\nYOUR LOOP.',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:Colors.white,height:1.0)),SizedBox(height:10),Text('Discover trending anime and stream from multiple sources.',style:TextStyle(color:Colors.white70)),SizedBox(height:14),Text('Use Browse to search and start watching.',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w700))]))]));}}
class PosterCard extends StatelessWidget{final AniListMedia media;const PosterCard({super.key,required this.media});@override Widget build(BuildContext c){return SizedBox(width:145,child:InkWell(onTap:()=>Get.to(()=>AniListDetails(media:media)),borderRadius:BorderRadius.circular(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.network(media.cover??'',fit:BoxFit.cover,width:145,errorBuilder:(_,__,___)=>Container(color:Theme.of(c).cardColor,child:const Icon(Icons.broken_image_rounded))))),const SizedBox(height:7),Text(media.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)),if(media.score!=null)Text('★ ${media.score}/100',style:const TextStyle(color:Themes.accent,fontSize:12,fontWeight:FontWeight.w700))])));}}
class AniListDetails extends StatelessWidget{final AniListMedia media;const AniListDetails({super.key,required this.media});@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text(media.title)),body:ListView(padding:const EdgeInsets.all(16),children:[ClipRRect(borderRadius:BorderRadius.circular(18),child:Image.network(media.banner??media.cover??'',height:190,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:190,color:Theme.of(c).cardColor))),const SizedBox(height:18),Text(media.title,style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[if(media.format!=null)Chip(label:Text(media.format!)),if(media.status!=null)Chip(label:Text(media.status!)),if(media.episodes!=null)Chip(label:Text('${media.episodes} eps')),if(media.score!=null)Chip(label:Text('★ ${media.score}'))]),const SizedBox(height:16),Text(media.description??'No description available.'),const SizedBox(height:18),Text('Genres',style:Theme.of(c).textTheme.titleMedium),const SizedBox(height:8),Wrap(spacing:6,children:media.genres.map((g)=>Chip(label:Text(g))).toList()),if(media.studio!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text('Studio: ${media.studio}'))]));}}

class AniLoopSearchDelegate extends SearchDelegate<AniListMedia?> {
  @override List<Widget>? buildActions(BuildContext context)=>[if(query.isNotEmpty)IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];
  @override Widget? buildLeading(BuildContext context)=>IconButton(onPressed:()=>close(context,null),icon:const Icon(Icons.arrow_back));
  @override Widget buildResults(BuildContext context)=>FutureBuilder<List<AniListMedia>>(future:AniListService.search(query),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Search unavailable. Check your connection.'));final items=s.data??[];if(items.isEmpty)return const Center(child:Text('No anime found'));return GridView.builder(padding:const EdgeInsets.all(14),gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:160,childAspectRatio:.58,crossAxisSpacing:12,mainAxisSpacing:14),itemCount:items.length,itemBuilder:(_,i)=>PosterCard(media:items[i]);});
  @override Widget buildSuggestions(BuildContext context)=>Center(child:Text(query.isEmpty?'Search anime, characters, titles...':'Press search to find "$query"'));
}
